### ISSUE TITLE
请问对于这种方式实现的动态爬虫如何做并发

### ISSUE THREAD

**Issue by mashaz** [Python3WebSpider/ScrapySeleniumTest#1]
settings.py里的CONCURRENT_REQUESTS在没有效果

**Comment by CIRCLECHAO** [comment]
我发觉用middleware的时候返回数据的时候 非常卡顿 不知道什么原因

**Comment by aesdhj** [comment]
> 我发觉用middleware的时候返回数据的时候 非常卡顿 不知道什么原因

我也在看这本书，为这本书建了一个QQ群805370297，方便大家讨论
